version: '3.4'

services:
  bikes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  client:
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./ClientApp:/app 